### ISSUE TITLE
Read product

### ISSUE THREAD

**Issue by tawn33y** [CSCI-GA-2820-SP24-003/products#12]
**As a** customer
**I need** to be able view/retrieve product details
**So that** I can learn more about an item I'm interested in, and then purchase or put it in my wishlist
   
 ### Details and Assumptions
 * There is a database table for the products data
 * Products should be identifiable by a unique SKU
 * A call to `GET /products/id` should retrieve the product with id `id`
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a valid product SKU
 When the product is read
 Then the according product data is returned, i.e. product name, description, price, and image 

When I call GET '/products/<id>'
Then it returns the corresponding product 
```

**Comment by jjeangal** [comment]
Verify if **As a** concerns the customer or engineers.
