### ISSUE TITLE
Categorize products

### ISSUE THREAD

**Issue by tawn33y** [CSCI-GA-2820-SP24-003/products#13]
**As a** store manager
**I need** to be able to categorize products
**So that** customers can browse items by categories.
   
 ### Details and Assumptions
 * There is database tables for products & categories data
 * Products should be identifiable by a unique SKU.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a product's SKU
 When a store manager assigns or edits a product's categories
 Then the product's categories fields are updated immediately
--
 Given a category
 When a customer views products by a certain category
 Then a list of products in that category are returned
```

**Comment by jjeangal** [comment]
Lies in the update product issue
