### ISSUE TITLE
Product Reviews

### ISSUE THREAD

**Issue by dheemutech** [CSCI-GA-2820-SP24-003/products#14]
As a customer
I need the ability to leave reviews and ratings for products
So that I can provide feedback and help others make informed purchase decisions.

### Details and Assumptions
 
Customers can leave a textual review and a star rating (1 to 5).
Reviews will be displayed on the product's page.
Users must have purchased the product to leave a review. 
  
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a purchased product's SKU and the user ID
When I submit a review and rating for the product
Then the review and rating should be saved and displayed with the product information
```

**Comment by jjeangal** [comment]
To merge with Ratings Issue #8
