### ISSUE TITLE
Product Availability

### ISSUE THREAD

**Issue by dheemutech** [CSCI-GA-2820-SP24-003/products#15]
As a customer
I need to see the availability status of products
So that I can decide whether to buy now, wait for restock, or pre-order.
   
 ### Details and Assumptions
Products will have one of the following statuses: "In Stock," "Out of Stock," "Pre-order."
Availability status is updated in real-time based on inventory levels.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a product's SKU
When I view a product
Then the product's availability status should be clearly displayed as "In Stock," "Out of Stock," or "Pre-order"
```

**Comment by jjeangal** [comment]
This issue is more related to the inventory team we believe.
