### ISSUE TITLE
Related Products

### ISSUE THREAD

**Issue by dheemutech** [CSCI-GA-2820-SP24-003/products#16]
**As a** store manager
**I need** to associate products with related items
**So that** customers can discover complementary products and increase the likelihood of cross-selling.  
   
 ### Details and Assumptions
* Related products are determined based on category, purchase history, or manual curation.
* Each product can have a list of related products.
* Related products should be easy to update and manage in the database.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a product's SKU
When I associate a list of related product SKUs in the system
Then these related products should be displayed when viewing the main product
```

**Comment by jjeangal** [comment]
For recommendations team
