### ISSUE TITLE
Create Products ORM model

### ISSUE THREAD

**Issue by va1shn9v** [CSCI-GA-2820-SP24-003/products#22]
**As a** Developer
**I need** a ORM data model 
**So that** I can define schema of the tables,create tables in the database and query them.
   
 ### Details and Assumptions
 * A postgreSQL Database is connected.
 * The table will have fields like id, product_name, Image_url, description, price, rating, category, status.
 *  Make changes to the `YourResourceModel` class in the the `services/models.py` to implement the specified data model
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given The data model is implemented
 When the app is run
 Then The database should have products table with dummy data

 When I make a API call 
 And Query the database using the ORM data model
 Then the requested changes to the data should be reflected in the database
```

**Comment by tawn33y** [comment]
Taking over from @va1shn9v
