### ISSUE TITLE
Create Project WebHook

### ISSUE THREAD

**Issue by jjeangal** [CSCI-GA-2820-SP24-003/products#37]
**As a** Developer
**I need** to create a WebHook on the class project repository
**So that** the pipeline is triggered automatically whenever a push is made to the master branch.
   
 ### Details and Assumptions
 * The WebHook will be configured to call the pipeline on push events to the master branch only.
 * The WebHook will be created using the GitHub UI.
 * The Maintainer of the repository will need to be temporarily promoted to Admin to establish the WebHook.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given that the Maintainer has been promoted to Admin and the pipeline is configured, 
When a push is made to the master branch,
Then the WebHook should trigger the pipeline automatically, that is, the pipeline should start running without any manual intervention.
```

**Comment by f0rgeAhead** [comment]
<img width="1544" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM21iQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--351e1043e503903e0699fc615ac57dcbc2dfe939/%E6%88%AA%E5%B1%8F2024-04-28%20%E4%B8%8A%E5%8D%8810.49.55.png" alt="截屏2024-04-28 上午10.49.55.png" />
