### ISSUE TITLE
Build a CD Pipeline

### ISSUE THREAD

**Issue by jjeangal** [CSCI-GA-2820-SP24-003/products#38]
**As a** developer
**I need** to create a .tekton folder and define pipeline, tasks and workspace
**So that** I can build and deploy my products microservice using a Tekton pipeline.

 ### Details and Assumptions

* The .tekton folder will store all pipeline artifacts including pipeline definition, task definitions and workspace definition.
* The pipeline definition will be stored in .tekton/pipeline.yaml file
* The task definitions will be stored in .tekton/tasks.yaml file
* The workspace definition will be stored in .tekton/workspace.yaml file
* Each task represents a single step in the pipeline, such as linting, testing, building, and deploying.
* The workspace is a shared storage space that can be accessed by all tasks in the pipeline.
* The pipeline, tasks and workspace will be defined using YAML and stored in the respective files in the .tekton folder in the root of the GitHub repository.
* A BASE_URL of the Kubernetes cluster should be passed to the pipeline, as it will be used by one of the tasks in the pipeline to run BDD tests against the deployment in OpenShift. The BDD tests task will require the BASE_URL as an argument or environment variable to correctly access the microservice.

 ### Acceptance Criteria  

 ```gherkin
Given:
- The .tekton folder is created and the pipeline, tasks and workspace definitions are stored in the respective files in the .tekton folder, and
- The BASE_URL is passed as an argument or environment variable when the pipeline is triggered

When the pipeline, tasks and workspace are applied to the OpenShift cluster

Then: 
- The pipeline is created and can be used to build and deploy the products microservice
- Tasks have access to shared storage space for storing and accessing data
- The BDD tests task uses the correct route to the microservice deployment in OpenShift, and 
- The BDD tests run successfully.
```

**Comment by f0rgeAhead** [comment]
<img width="1225" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3ViQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc9259e0928b8cf9f877c63d4ada34d702b7bc03/%E6%88%AA%E5%B1%8F2024-04-28%20%E4%B8%8A%E5%8D%8810.50.46.png" alt="截屏2024-04-28 上午10.50.46.png" />
<img width="1818" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3liQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1e0f207cf91dc1589604a1a283ce17d8024dffb/%E6%88%AA%E5%B1%8F2024-04-28%20%E4%B8%8A%E5%8D%8810.50.37.png" alt="截屏2024-04-28 上午10.50.37.png" />
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzJiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23ee5cc1e191eeeb8d88992ee4d7f4dcc3467d42/%E6%88%AA%E5%B1%8F2024-04-28%20%E4%B8%8A%E5%8D%8810.50.28.png" alt="截屏2024-04-28 上午10.50.28.png" />
