### ISSUE TITLE
Read Product in detail on the UI

### ISSUE THREAD

**Issue by f0rgeAhead** [CSCI-GA-2820-SP24-003/products#45]
**As a** eCommerce manager,
**I need** to view details of defined product items,
**So that** I can manage and review the catalog effectively.

 ### Details and Assumptions
* Each item in the products list should have a detail view.

 ### Acceptance Criteria

 ```gherkin
Given an item exists in the system,
When I select an item,
Then I see its detailed information.
 ```

**Comment by jjeangal** [comment]
Delivered in issue #46, adding an extra button and modal would be a redundancy.
