### ISSUE TITLE
List Products Catalog on the UI

### ISSUE THREAD

**Issue by f0rgeAhead** [CSCI-GA-2820-SP24-003/products#48]
**As a** eCommerce manager,
**I need** to view a list of all inventory items,
**So that** I can easily browse and manage the catalog.

 ### Details and Assumptions
* The UI displays a complete list of inventory items.

 ### Acceptance Criteria

 ```gherkin
Given items exist in the inventory,
When I navigate to the inventory list page,
Then I see all items listed.
 ```

**Comment by tawn33y** [comment]
Does this refer to listing all available products? Or is it for getting data from the inventory team, which means we shouldn't be working on it now?
@f0rgeAhead @va1shn9v @jjeangal

**Comment by jjeangal** [comment]
I believe it should be changed to the product catalog as we are not responsible for the inventory.
