### ISSUE TITLE
Set up Event Listener

### ISSUE THREAD

**Issue by jjeangal** [CSCI-GA-2820-SP24-003/products#55]
**As a** Developer
**I need** to set up an EventListener with a Trigger, TriggerBinding, and TriggerTemplate that creates a PipelineRun to run the pipeline
**So that** the pipeline can be automatically triggered by specific events.
   
 ### Details and Assumptions
* The EventListener will listen for specific events, such as a GitHub webhook.
* The Trigger will define the conditions under which the pipeline should be triggered.
* The TriggerBinding will specify the parameters that should be passed to the pipeline.
* The TriggerTemplate will define the PipelineRun that should be created when the trigger is activated.
* The pipeline has already been created and is stored in the .tekton/ folder.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given that the EventListener, Trigger, TriggerBinding, and TriggerTemplate files are stored in the .tekton/ folder and the pipeline is available,
When the specified event occurs,
Then the Trigger should activate and create a PipelineRun using the TriggerTemplate. The PipelineRun should start running the pipeline with the specified parameters. The pipeline should complete successfully and produce the expected results.
```

**Comment by f0rgeAhead** [comment]
<img width="1366" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2liQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cbdf6123f2ff6ae9525fae8e1d4053857f21b120/%E6%88%AA%E5%B1%8F2024-04-28%20%E4%B8%8A%E5%8D%8810.49.09.png" alt="截屏2024-04-28 上午10.49.09.png" />

**Comment by jjeangal** [comment]
Amazing stuff!

**Comment by jjeangal** [comment]
I can't really see the image on github tho

**Comment by f0rgeAhead** [comment]
Image is in `deployment.yaml` file.
